name: seq_gr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
    - rdkit
    - python=3.7.3
    - pytorch=1.7.0
    - cudatoolkit=10.1.243
    - pip
    - pip:
        - networkx
        - wandb
        - joblib
        - tqdm
